### ISSUE TITLE
SDK closes in iPhoneX and above

### ISSUE THREAD

**Issue by Neeraj204** [cashfree/ios-CFWebSDK#27]
Hello,
My app is live and right now found new issue, whenever I initiate SDK for the payment after getting token, the SDK suddenly closes after opening. This issue only occurs in iPhoneX, XR and above devices. In simulator, working fine. Also I'm using the latest SDK.

**Comment by arjun-cashfree** [comment]
Neeraj,

Please use the CFSDK.xcframework file from this repo. We can see that you are using CFSDK.framework from the other ticket you have raised. If you are still facing any issues, please contact techsupport@cashfree.com and we'll help you with the integration.

**Comment by Neeraj204** [comment]
I am only using CFSDK.xcframework and that app is already live, now all of sudden payment page closes just after opening. And why are you closing issue eveytime? Is that the thing how you support the people?

**Comment by arjun-cashfree** [comment]
This is an integration issue. If the screen is closing right after opening, then something must be wrong with either your account setup or the input being passed to the SDK. In both cases you'll get the reason for failure in the response. 

I'm closing the ticket because it is an integration query and not an issue in the SDK. But please reach out to our tech support and we'll gladly help you out fixing this issue.

**Comment by Neeraj204** [comment]
But it works in some devices and only happens with devices like iPhone X, iPhone XR. If it is related to wrong integration or account setup it should not work in all the device right?
